# Generated by Django 2.2 on 2019-05-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('t1', 'Team #ForTheKids'), ('t2', 'B-Rate Anime Club'), ('t3', "Team Breaking Dustin's Back")], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.BigIntegerField(default=1000),
        ),
    ]
