# Generated by Django 2.2 on 2019-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190501_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('Team #ForTheKids', 'Team #ForTheKids'), ('B-Rate Anime Club', 'B-Rate Anime Club'), ("Team Breaking Dustin's Back", "Team Breaking Dustin's Back")], max_length=50),
        ),
    ]
